#!/bin/bash

make clean

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile

cd src

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile

cd core

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile

cd ../util

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile

cd ../vendor

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile

cd glad

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile

cd ../../game

rm -r CMakeFiles cmake_install.cmake CMakeCache.txt Makefile
